/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.dawn.dawn.DawnPackage;
import org.xtext.example.dawn.dawn.PositionAttribute;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Position Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.impl.PositionAttributeImpl#getPositionEnum <em>Position Enum</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PositionAttributeImpl extends MinimalEObjectImpl.Container implements PositionAttribute
{
  /**
   * The default value of the '{@link #getPositionEnum() <em>Position Enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositionEnum()
   * @generated
   * @ordered
   */
  protected static final String POSITION_ENUM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPositionEnum() <em>Position Enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositionEnum()
   * @generated
   * @ordered
   */
  protected String positionEnum = POSITION_ENUM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PositionAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DawnPackage.Literals.POSITION_ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPositionEnum()
  {
    return positionEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPositionEnum(String newPositionEnum)
  {
    String oldPositionEnum = positionEnum;
    positionEnum = newPositionEnum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DawnPackage.POSITION_ATTRIBUTE__POSITION_ENUM, oldPositionEnum, positionEnum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DawnPackage.POSITION_ATTRIBUTE__POSITION_ENUM:
        return getPositionEnum();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DawnPackage.POSITION_ATTRIBUTE__POSITION_ENUM:
        setPositionEnum((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DawnPackage.POSITION_ATTRIBUTE__POSITION_ENUM:
        setPositionEnum(POSITION_ENUM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DawnPackage.POSITION_ATTRIBUTE__POSITION_ENUM:
        return POSITION_ENUM_EDEFAULT == null ? positionEnum != null : !POSITION_ENUM_EDEFAULT.equals(positionEnum);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (positionEnum: ");
    result.append(positionEnum);
    result.append(')');
    return result.toString();
  }

} //PositionAttributeImpl
