/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn;

import org.xtext.example.dawn.DawnStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DawnStandaloneSetup extends DawnStandaloneSetupGenerated {
  public static void doSetup() {
    DawnStandaloneSetup _dawnStandaloneSetup = new DawnStandaloneSetup();
    _dawnStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
