/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button Attributes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.ButtonAttributes#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.example.dawn.dawn.ButtonAttributes#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dawn.dawn.DawnPackage#getButtonAttributes()
 * @model
 * @generated
 */
public interface ButtonAttributes extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(TextAttribute)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getButtonAttributes_Text()
   * @model containment="true"
   * @generated
   */
  TextAttribute getText();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.ButtonAttributes#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(TextAttribute value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' containment reference.
   * @see #setMethod(Call)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getButtonAttributes_Method()
   * @model containment="true"
   * @generated
   */
  Call getMethod();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.ButtonAttributes#getMethod <em>Method</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' containment reference.
   * @see #getMethod()
   * @generated
   */
  void setMethod(Call value);

} // ButtonAttributes
