/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.dawn.dawn.DawnFactory
 * @model kind="package"
 * @generated
 */
public interface DawnPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dawn";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/dawn/Dawn";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dawn";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DawnPackage eINSTANCE = org.xtext.example.dawn.dawn.impl.DawnPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ModelImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Window</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WINDOW = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.WindowImpl <em>Window</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.WindowImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getWindow()
   * @generated
   */
  int WINDOW = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__CONTAINER = 2;

  /**
   * The number of structural features of the '<em>Window</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ComponentImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.WindowAttributesImpl <em>Window Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.WindowAttributesImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getWindowAttributes()
   * @generated
   */
  int WINDOW_ATTRIBUTES = 3;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_ATTRIBUTES__TEXT = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_ATTRIBUTES__SIZE = 1;

  /**
   * The number of structural features of the '<em>Window Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_ATTRIBUTES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.TextAttributeImpl <em>Text Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.TextAttributeImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextAttribute()
   * @generated
   */
  int TEXT_ATTRIBUTE = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_ATTRIBUTE__TEXT = 0;

  /**
   * The number of structural features of the '<em>Text Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_ATTRIBUTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.SizeAttributeImpl <em>Size Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.SizeAttributeImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSizeAttribute()
   * @generated
   */
  int SIZE_ATTRIBUTE = 5;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_ATTRIBUTE__HEIGHT = 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_ATTRIBUTE__WIDTH = 1;

  /**
   * The number of structural features of the '<em>Size Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ContainerImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 6;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ElementImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Component</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__COMPONENT = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__POSITION = 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__SIZE = 2;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.PositionAttributeImpl <em>Position Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.PositionAttributeImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getPositionAttribute()
   * @generated
   */
  int POSITION_ATTRIBUTE = 8;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_ATTRIBUTE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_ATTRIBUTE__Y = 1;

  /**
   * The number of structural features of the '<em>Position Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ButtonImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__ATTRIBUTES = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.ButtonAttributesImpl <em>Button Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.ButtonAttributesImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getButtonAttributes()
   * @generated
   */
  int BUTTON_ATTRIBUTES = 10;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_ATTRIBUTES__TEXT = 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_ATTRIBUTES__METHOD = 1;

  /**
   * The number of structural features of the '<em>Button Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_ATTRIBUTES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.TextFieldImpl <em>Text Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.TextFieldImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextField()
   * @generated
   */
  int TEXT_FIELD = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FIELD__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FIELD__TEXT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FIELD_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.TextLabelImpl <em>Text Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.TextLabelImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextLabel()
   * @generated
   */
  int TEXT_LABEL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LABEL__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LABEL__TEXT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LABEL_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.PasswordFieldImpl <em>Password Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.PasswordFieldImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getPasswordField()
   * @generated
   */
  int PASSWORD_FIELD = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD_FIELD__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD_FIELD__TEXT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Password Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD_FIELD_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceImpl <em>Single Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.SingleChoiceImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoice()
   * @generated
   */
  int SINGLE_CHOICE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE__ATTRIBUTES = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Single Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceAttributesImpl <em>Single Choice Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.SingleChoiceAttributesImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoiceAttributes()
   * @generated
   */
  int SINGLE_CHOICE_ATTRIBUTES = 15;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_ATTRIBUTES__TEXT = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_ATTRIBUTES__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Single Choice Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_ATTRIBUTES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceOptionsImpl <em>Single Choice Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.dawn.dawn.impl.SingleChoiceOptionsImpl
   * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoiceOptions()
   * @generated
   */
  int SINGLE_CHOICE_OPTIONS = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_OPTIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_OPTIONS__TEXT = 1;

  /**
   * The number of structural features of the '<em>Single Choice Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_CHOICE_OPTIONS_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.dawn.dawn.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dawn.dawn.Model#getWindow <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Window</em>'.
   * @see org.xtext.example.dawn.dawn.Model#getWindow()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Window();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dawn.dawn.Model#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.xtext.example.dawn.dawn.Model#getComponents()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Components();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Window <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Window</em>'.
   * @see org.xtext.example.dawn.dawn.Window
   * @generated
   */
  EClass getWindow();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.Window#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dawn.dawn.Window#getName()
   * @see #getWindow()
   * @generated
   */
  EAttribute getWindow_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Window#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.Window#getAttributes()
   * @see #getWindow()
   * @generated
   */
  EReference getWindow_Attributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Window#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.example.dawn.dawn.Window#getContainer()
   * @see #getWindow()
   * @generated
   */
  EReference getWindow_Container();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.example.dawn.dawn.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dawn.dawn.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.WindowAttributes <em>Window Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Window Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.WindowAttributes
   * @generated
   */
  EClass getWindowAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.WindowAttributes#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.WindowAttributes#getText()
   * @see #getWindowAttributes()
   * @generated
   */
  EReference getWindowAttributes_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.WindowAttributes#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.dawn.dawn.WindowAttributes#getSize()
   * @see #getWindowAttributes()
   * @generated
   */
  EReference getWindowAttributes_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.TextAttribute <em>Text Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Attribute</em>'.
   * @see org.xtext.example.dawn.dawn.TextAttribute
   * @generated
   */
  EClass getTextAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.TextAttribute#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.TextAttribute#getText()
   * @see #getTextAttribute()
   * @generated
   */
  EAttribute getTextAttribute_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.SizeAttribute <em>Size Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size Attribute</em>'.
   * @see org.xtext.example.dawn.dawn.SizeAttribute
   * @generated
   */
  EClass getSizeAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.SizeAttribute#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.xtext.example.dawn.dawn.SizeAttribute#getHeight()
   * @see #getSizeAttribute()
   * @generated
   */
  EAttribute getSizeAttribute_Height();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.SizeAttribute#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.xtext.example.dawn.dawn.SizeAttribute#getWidth()
   * @see #getSizeAttribute()
   * @generated
   */
  EAttribute getSizeAttribute_Width();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.example.dawn.dawn.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dawn.dawn.Container#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.dawn.dawn.Container#getElements()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.dawn.dawn.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Element#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Component</em>'.
   * @see org.xtext.example.dawn.dawn.Element#getComponent()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Component();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Element#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see org.xtext.example.dawn.dawn.Element#getPosition()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Position();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Element#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.xtext.example.dawn.dawn.Element#getSize()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.PositionAttribute <em>Position Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Position Attribute</em>'.
   * @see org.xtext.example.dawn.dawn.PositionAttribute
   * @generated
   */
  EClass getPositionAttribute();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.dawn.dawn.PositionAttribute#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>X</em>'.
   * @see org.xtext.example.dawn.dawn.PositionAttribute#getX()
   * @see #getPositionAttribute()
   * @generated
   */
  EAttribute getPositionAttribute_X();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.dawn.dawn.PositionAttribute#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Y</em>'.
   * @see org.xtext.example.dawn.dawn.PositionAttribute#getY()
   * @see #getPositionAttribute()
   * @generated
   */
  EAttribute getPositionAttribute_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.example.dawn.dawn.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.Button#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.Button#getAttributes()
   * @see #getButton()
   * @generated
   */
  EReference getButton_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.ButtonAttributes <em>Button Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.ButtonAttributes
   * @generated
   */
  EClass getButtonAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.ButtonAttributes#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.ButtonAttributes#getText()
   * @see #getButtonAttributes()
   * @generated
   */
  EReference getButtonAttributes_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.ButtonAttributes#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see org.xtext.example.dawn.dawn.ButtonAttributes#getMethod()
   * @see #getButtonAttributes()
   * @generated
   */
  EReference getButtonAttributes_Method();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.TextField <em>Text Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Field</em>'.
   * @see org.xtext.example.dawn.dawn.TextField
   * @generated
   */
  EClass getTextField();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.TextField#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.TextField#getText()
   * @see #getTextField()
   * @generated
   */
  EReference getTextField_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.TextLabel <em>Text Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Label</em>'.
   * @see org.xtext.example.dawn.dawn.TextLabel
   * @generated
   */
  EClass getTextLabel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.TextLabel#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.TextLabel#getText()
   * @see #getTextLabel()
   * @generated
   */
  EReference getTextLabel_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.PasswordField <em>Password Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Password Field</em>'.
   * @see org.xtext.example.dawn.dawn.PasswordField
   * @generated
   */
  EClass getPasswordField();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.PasswordField#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.PasswordField#getText()
   * @see #getPasswordField()
   * @generated
   */
  EReference getPasswordField_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.SingleChoice <em>Single Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Choice</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoice
   * @generated
   */
  EClass getSingleChoice();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.SingleChoice#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoice#getAttributes()
   * @see #getSingleChoice()
   * @generated
   */
  EReference getSingleChoice_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.SingleChoiceAttributes <em>Single Choice Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Choice Attributes</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceAttributes
   * @generated
   */
  EClass getSingleChoiceAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.SingleChoiceAttributes#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceAttributes#getText()
   * @see #getSingleChoiceAttributes()
   * @generated
   */
  EReference getSingleChoiceAttributes_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.dawn.dawn.SingleChoiceAttributes#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceAttributes#getComponents()
   * @see #getSingleChoiceAttributes()
   * @generated
   */
  EReference getSingleChoiceAttributes_Components();

  /**
   * Returns the meta object for class '{@link org.xtext.example.dawn.dawn.SingleChoiceOptions <em>Single Choice Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Choice Options</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceOptions
   * @generated
   */
  EClass getSingleChoiceOptions();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.dawn.dawn.SingleChoiceOptions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceOptions#getName()
   * @see #getSingleChoiceOptions()
   * @generated
   */
  EAttribute getSingleChoiceOptions_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.dawn.dawn.SingleChoiceOptions#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.dawn.dawn.SingleChoiceOptions#getText()
   * @see #getSingleChoiceOptions()
   * @generated
   */
  EReference getSingleChoiceOptions_Text();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DawnFactory getDawnFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ModelImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Window</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WINDOW = eINSTANCE.getModel_Window();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMPONENTS = eINSTANCE.getModel_Components();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.WindowImpl <em>Window</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.WindowImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getWindow()
     * @generated
     */
    EClass WINDOW = eINSTANCE.getWindow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINDOW__NAME = eINSTANCE.getWindow_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW__ATTRIBUTES = eINSTANCE.getWindow_Attributes();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW__CONTAINER = eINSTANCE.getWindow_Container();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ComponentImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.WindowAttributesImpl <em>Window Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.WindowAttributesImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getWindowAttributes()
     * @generated
     */
    EClass WINDOW_ATTRIBUTES = eINSTANCE.getWindowAttributes();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW_ATTRIBUTES__TEXT = eINSTANCE.getWindowAttributes_Text();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW_ATTRIBUTES__SIZE = eINSTANCE.getWindowAttributes_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.TextAttributeImpl <em>Text Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.TextAttributeImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextAttribute()
     * @generated
     */
    EClass TEXT_ATTRIBUTE = eINSTANCE.getTextAttribute();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_ATTRIBUTE__TEXT = eINSTANCE.getTextAttribute_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.SizeAttributeImpl <em>Size Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.SizeAttributeImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSizeAttribute()
     * @generated
     */
    EClass SIZE_ATTRIBUTE = eINSTANCE.getSizeAttribute();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_ATTRIBUTE__HEIGHT = eINSTANCE.getSizeAttribute_Height();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_ATTRIBUTE__WIDTH = eINSTANCE.getSizeAttribute_Width();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ContainerImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__ELEMENTS = eINSTANCE.getContainer_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ElementImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__COMPONENT = eINSTANCE.getElement_Component();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__POSITION = eINSTANCE.getElement_Position();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__SIZE = eINSTANCE.getElement_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.PositionAttributeImpl <em>Position Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.PositionAttributeImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getPositionAttribute()
     * @generated
     */
    EClass POSITION_ATTRIBUTE = eINSTANCE.getPositionAttribute();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION_ATTRIBUTE__X = eINSTANCE.getPositionAttribute_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION_ATTRIBUTE__Y = eINSTANCE.getPositionAttribute_Y();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ButtonImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__ATTRIBUTES = eINSTANCE.getButton_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.ButtonAttributesImpl <em>Button Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.ButtonAttributesImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getButtonAttributes()
     * @generated
     */
    EClass BUTTON_ATTRIBUTES = eINSTANCE.getButtonAttributes();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON_ATTRIBUTES__TEXT = eINSTANCE.getButtonAttributes_Text();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON_ATTRIBUTES__METHOD = eINSTANCE.getButtonAttributes_Method();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.TextFieldImpl <em>Text Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.TextFieldImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextField()
     * @generated
     */
    EClass TEXT_FIELD = eINSTANCE.getTextField();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_FIELD__TEXT = eINSTANCE.getTextField_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.TextLabelImpl <em>Text Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.TextLabelImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getTextLabel()
     * @generated
     */
    EClass TEXT_LABEL = eINSTANCE.getTextLabel();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_LABEL__TEXT = eINSTANCE.getTextLabel_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.PasswordFieldImpl <em>Password Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.PasswordFieldImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getPasswordField()
     * @generated
     */
    EClass PASSWORD_FIELD = eINSTANCE.getPasswordField();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PASSWORD_FIELD__TEXT = eINSTANCE.getPasswordField_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceImpl <em>Single Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.SingleChoiceImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoice()
     * @generated
     */
    EClass SINGLE_CHOICE = eINSTANCE.getSingleChoice();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CHOICE__ATTRIBUTES = eINSTANCE.getSingleChoice_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceAttributesImpl <em>Single Choice Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.SingleChoiceAttributesImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoiceAttributes()
     * @generated
     */
    EClass SINGLE_CHOICE_ATTRIBUTES = eINSTANCE.getSingleChoiceAttributes();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CHOICE_ATTRIBUTES__TEXT = eINSTANCE.getSingleChoiceAttributes_Text();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CHOICE_ATTRIBUTES__COMPONENTS = eINSTANCE.getSingleChoiceAttributes_Components();

    /**
     * The meta object literal for the '{@link org.xtext.example.dawn.dawn.impl.SingleChoiceOptionsImpl <em>Single Choice Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.dawn.dawn.impl.SingleChoiceOptionsImpl
     * @see org.xtext.example.dawn.dawn.impl.DawnPackageImpl#getSingleChoiceOptions()
     * @generated
     */
    EClass SINGLE_CHOICE_OPTIONS = eINSTANCE.getSingleChoiceOptions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_CHOICE_OPTIONS__NAME = eINSTANCE.getSingleChoiceOptions_Name();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_CHOICE_OPTIONS__TEXT = eINSTANCE.getSingleChoiceOptions_Text();

  }

} //DawnPackage
