/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gap Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.GapAttribute#getGapWidth <em>Gap Width</em>}</li>
 *   <li>{@link org.xtext.example.dawn.dawn.GapAttribute#getGapHeight <em>Gap Height</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dawn.dawn.DawnPackage#getGapAttribute()
 * @model
 * @generated
 */
public interface GapAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Gap Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gap Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gap Width</em>' attribute.
   * @see #setGapWidth(int)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getGapAttribute_GapWidth()
   * @model
   * @generated
   */
  int getGapWidth();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.GapAttribute#getGapWidth <em>Gap Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gap Width</em>' attribute.
   * @see #getGapWidth()
   * @generated
   */
  void setGapWidth(int value);

  /**
   * Returns the value of the '<em><b>Gap Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gap Height</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gap Height</em>' attribute.
   * @see #setGapHeight(int)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getGapAttribute_GapHeight()
   * @model
   * @generated
   */
  int getGapHeight();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.GapAttribute#getGapHeight <em>Gap Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gap Height</em>' attribute.
   * @see #getGapHeight()
   * @generated
   */
  void setGapHeight(int value);

} // GapAttribute
