/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.PositionAttribute#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.dawn.dawn.PositionAttribute#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dawn.dawn.DawnPackage#getPositionAttribute()
 * @model
 * @generated
 */
public interface PositionAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute list.
   * @see org.xtext.example.dawn.dawn.DawnPackage#getPositionAttribute_X()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getX();

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Y</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute list.
   * @see org.xtext.example.dawn.dawn.DawnPackage#getPositionAttribute_Y()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getY();

} // PositionAttribute
