/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.PositionAttribute#getPositionEnum <em>Position Enum</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dawn.dawn.DawnPackage#getPositionAttribute()
 * @model
 * @generated
 */
public interface PositionAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Position Enum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Position Enum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position Enum</em>' attribute.
   * @see #setPositionEnum(String)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getPositionAttribute_PositionEnum()
   * @model
   * @generated
   */
  String getPositionEnum();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.PositionAttribute#getPositionEnum <em>Position Enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position Enum</em>' attribute.
   * @see #getPositionEnum()
   * @generated
   */
  void setPositionEnum(String value);

} // PositionAttribute
