/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.dawn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dawn.dawn.SingleChoice#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dawn.dawn.DawnPackage#getSingleChoice()
 * @model
 * @generated
 */
public interface SingleChoice extends Component
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference.
   * @see #setAttributes(SingleChoiceAttributes)
   * @see org.xtext.example.dawn.dawn.DawnPackage#getSingleChoice_Attributes()
   * @model containment="true"
   * @generated
   */
  SingleChoiceAttributes getAttributes();

  /**
   * Sets the value of the '{@link org.xtext.example.dawn.dawn.SingleChoice#getAttributes <em>Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attributes</em>' containment reference.
   * @see #getAttributes()
   * @generated
   */
  void setAttributes(SingleChoiceAttributes value);

} // SingleChoice
