/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDawnScopeProvider extends DelegatingScopeProvider {
}
