/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.dawn


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DawnStandaloneSetup extends DawnStandaloneSetupGenerated {

	def static void doSetup() {
		new DawnStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
